// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ousjuessjemtudwzroyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91c2p1ZXNzamVtdHVkd3pyb3l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDI1MjgsImV4cCI6MjA3MjExODUyOH0.gXN2y5QmH9gDHJYsx7ksPRWA_w-4RiBGbVZRRTtrCiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});